language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
    - pip install -U pip wheel setuptools codecov

install:
    - pip install -r reqs/requirements-latest.txt -r reqs/requirements-tests.txt

script:
    - coverage erase
    - coverage run --branch bin/trial scrapyd
    - coverage report

after_success:
    - codecov

#notifications:
    #irc:
        #channels:
            #- "irc.freenode.org#scrapy"
        #use_notice: true
        #skip_join: true
